In [1]:
import pandas as pd
import numpy as np

print("Pandas version:", pd.__version__)
print("Ready to go!")

Pandas version: 3.0.2
Ready to go!

In [2]:
data = {
    'Name':       ['Ama', 'Kofi', 'Abena', 'Kwame', 'Efua'],
    'Age':        [24, 31, 27, 35, 22],
    'Department': ['Sales', 'Tech', 'Sales', 'HR', 'Tech'],
    'Salary':     [3200, 5800, 3900, 4500, 5100],
    'Years':      [1, 6, 3, 8, 2]
}

df = pd.DataFrame(data)
df

    Name  Age Department  Salary  Years
0    Ama   24      Sales    3200      1
1   Kofi   31       Tech    5800      6
2  Abena   27      Sales    3900      3
3  Kwame   35         HR    4500      8
4   Efua   22       Tech    5100      2

In [3]:
df.shape

(5, 5)

In [4]:
df.columns

Index(['Name', 'Age', 'Department', 'Salary', 'Years'], dtype='str')

In [5]:
df.dtypes

Name            str
Age           int64
Department      str
Salary        int64
Years         int64
dtype: object

In [6]:
df.describe()

             Age       Salary     Years
count   5.000000     5.000000  5.000000
mean   27.800000  4500.000000  4.000000
std     5.263079  1012.422837  2.915476
min    22.000000  3200.000000  1.000000
25%    24.000000  3900.000000  2.000000
50%    27.000000  4500.000000  3.000000
75%    31.000000  5100.000000  6.000000
max    35.000000  5800.000000  8.000000

In [7]:
df.head(3)

    Name  Age Department  Salary  Years
0    Ama   24      Sales    3200      1
1   Kofi   31       Tech    5800      6
2  Abena   27      Sales    3900      3

In [8]:
df['Name']

0      Ama
1     Kofi
2    Abena
3    Kwame
4     Efua
Name: Name, dtype: str

In [9]:
df[['Name', 'Salary']]

    Name  Salary
0    Ama    3200
1   Kofi    5800
2  Abena    3900
3  Kwame    4500
4   Efua    5100

In [10]:
df[df['Salary'] > 4000]

    Name  Age Department  Salary  Years
1   Kofi   31       Tech    5800      6
3  Kwame   35         HR    4500      8
4   Efua   22       Tech    5100      2

In [11]:
df[(df['Department'] == 'Tech') & (df['Salary'] > 5000)]

   Name  Age Department  Salary  Years
1  Kofi   31       Tech    5800      6
4  Efua   22       Tech    5100      2

In [12]:
df[(df['Department'] == 'Sales') | (df['Department'] == 'HR')]

    Name  Age Department  Salary  Years
0    Ama   24      Sales    3200      1
2  Abena   27      Sales    3900      3
3  Kwame   35         HR    4500      8

In [13]:
df['Monthly_Salary'] = df['Salary'] / 12
df

    Name  Age Department  Salary  Years  Monthly_Salary
0    Ama   24      Sales    3200      1      266.666667
1   Kofi   31       Tech    5800      6      483.333333
2  Abena   27      Sales    3900      3      325.000000
3  Kwame   35         HR    4500      8      375.000000
4   Efua   22       Tech    5100      2      425.000000

In [14]:
df['Bonus'] = df['Salary'] * 0.10
df

    Name  Age Department  Salary  Years  Monthly_Salary  Bonus
0    Ama   24      Sales    3200      1      266.666667  320.0
1   Kofi   31       Tech    5800      6      483.333333  580.0
2  Abena   27      Sales    3900      3      325.000000  390.0
3  Kwame   35         HR    4500      8      375.000000  450.0
4   Efua   22       Tech    5100      2      425.000000  510.0

In [15]:
df['Level'] = df['Years'].apply(lambda x: 'Senior' if x >= 5 else 'Junior')
df

    Name  Age Department  Salary  Years  Monthly_Salary  Bonus   Level
0    Ama   24      Sales    3200      1      266.666667  320.0  Junior
1   Kofi   31       Tech    5800      6      483.333333  580.0  Senior
2  Abena   27      Sales    3900      3      325.000000  390.0  Junior
3  Kwame   35         HR    4500      8      375.000000  450.0  Senior
4   Efua   22       Tech    5100      2      425.000000  510.0  Junior

In [16]:
df.groupby('Department')['Salary'].mean()

Department
HR       4500.0
Sales    3550.0
Tech     5450.0
Name: Salary, dtype: float64

In [17]:
df.groupby('Department')['Salary'].sum()

Department
HR        4500
Sales     7100
Tech     10900
Name: Salary, dtype: int64

In [18]:
df.groupby('Department')['Salary'].agg(['mean', 'min', 'max', 'count'])

              mean   min   max  count
Department
HR          4500.0  4500  4500      1
Sales       3550.0  3200  3900      2
Tech        5450.0  5100  5800      2

In [19]:
# Sort by salary highest to lowest
df.sort_values('Salary', ascending=False)

    Name  Age Department  Salary  Years  Monthly_Salary  Bonus   Level
1   Kofi   31       Tech    5800      6      483.333333  580.0  Senior
4   Efua   22       Tech    5100      2      425.000000  510.0  Junior
3  Kwame   35         HR    4500      8      375.000000  450.0  Senior
2  Abena   27      Sales    3900      3      325.000000  390.0  Junior
0    Ama   24      Sales    3200      1      266.666667  320.0  Junior

In [20]:
# Sort by department, then salary
df.sort_values(['Department', 'Salary'], ascending=[True, False])

    Name  Age Department  Salary  Years  Monthly_Salary  Bonus   Level
3  Kwame   35         HR    4500      8      375.000000  450.0  Senior
2  Abena   27      Sales    3900      3      325.000000  390.0  Junior
0    Ama   24      Sales    3200      1      266.666667  320.0  Junior
1   Kofi   31       Tech    5800      6      483.333333  580.0  Senior
4   Efua   22       Tech    5100      2      425.000000  510.0  Junior