In [1]:
import pandas as pd
import numpy as np

data = {
    'Name':       ['Ama', 'Kofi', None, 'Kwame', 'Efua', 'Ama'],
    'Age':        [24, 31, 27, None, 22, 24],
    'Department': ['Sales', 'tech', 'Sales', 'HR', 'TECH', 'Sales'],
    'Salary':     [3200, 5800, 3900, 4500, None, 3200],
    'Email':      ['ama@gmail.com', 'kofi@gmail.com', 'abena@gmail.com', 
                   'kwame@gmail.com', 'efua@gmail.com', 'ama@gmail.com']
}

df = pd.DataFrame(data)
df

    Name   Age Department  Salary            Email
0    Ama  24.0      Sales  3200.0    ama@gmail.com
1   Kofi  31.0       tech  5800.0   kofi@gmail.com
2    NaN  27.0      Sales  3900.0  abena@gmail.com
3  Kwame   NaN         HR  4500.0  kwame@gmail.com
4   Efua  22.0       TECH     NaN   efua@gmail.com
5    Ama  24.0      Sales  3200.0    ama@gmail.com

In [2]:
df.isnull().sum()

Name          1
Age           1
Department    0
Salary        1
Email         0
dtype: int64

In [3]:
df[df['Name'].isnull()]

  Name   Age Department  Salary            Email
2  NaN  27.0      Sales  3900.0  abena@gmail.com

In [4]:
df['Name'] = df['Name'].fillna('Unknown')

In [5]:
df['Salary'] = df['Salary'].fillna(df['Salary'].mean())

In [6]:
df['Age'] = df['Age'].fillna(df['Age'].mean())

In [7]:
df.isnull().sum()

Name          0
Age           0
Department    0
Salary        0
Email         0
dtype: int64

In [8]:
# Check for duplicates
df.duplicated().sum()

np.int64(1)

In [9]:
df = df.drop_duplicates()
df

      Name   Age Department  Salary            Email
0      Ama  24.0      Sales  3200.0    ama@gmail.com
1     Kofi  31.0       tech  5800.0   kofi@gmail.com
2  Unknown  27.0      Sales  3900.0  abena@gmail.com
3    Kwame  25.6         HR  4500.0  kwame@gmail.com
4     Efua  22.0       TECH  4120.0   efua@gmail.com

In [10]:
df['Department'] = df['Department'].str.title()
df

      Name   Age Department  Salary            Email
0      Ama  24.0      Sales  3200.0    ama@gmail.com
1     Kofi  31.0       Tech  5800.0   kofi@gmail.com
2  Unknown  27.0      Sales  3900.0  abena@gmail.com
3    Kwame  25.6         Hr  4500.0  kwame@gmail.com
4     Efua  22.0       Tech  4120.0   efua@gmail.com

In [11]:
# Check current types
df.dtypes

Name              str
Age           float64
Department        str
Salary        float64
Email             str
dtype: object

In [12]:
df['Age'] = df['Age'].astype(int)
df.dtypes

Name              str
Age             int64
Department        str
Salary        float64
Email             str
dtype: object

In [13]:
df

      Name  Age Department  Salary            Email
0      Ama   24      Sales  3200.0    ama@gmail.com
1     Kofi   31       Tech  5800.0   kofi@gmail.com
2  Unknown   27      Sales  3900.0  abena@gmail.com
3    Kwame   25         Hr  4500.0  kwame@gmail.com
4     Efua   22       Tech  4120.0   efua@gmail.com

In [14]:
df['Department'] = df['Department'].replace('Hr', 'HR')
df

      Name  Age Department  Salary            Email
0      Ama   24      Sales  3200.0    ama@gmail.com
1     Kofi   31       Tech  5800.0   kofi@gmail.com
2  Unknown   27      Sales  3900.0  abena@gmail.com
3    Kwame   25         HR  4500.0  kwame@gmail.com
4     Efua   22       Tech  4120.0   efua@gmail.com