In [1]:
import pandas as pd
import numpy as np

# Employees table
employees = pd.DataFrame({
    'emp_id':     [1, 2, 3, 4, 5],
    'Name':       ['Ama', 'Kofi', 'Abena', 'Kwame', 'Efua'],
    'dept_id':    [101, 102, 101, 103, 102],
    'Salary':     [3200, 5800, 3900, 4500, 5100]
})

# Departments table
departments = pd.DataFrame({
    'dept_id':    [101, 102, 103, 104],
    'Department': ['Sales', 'Tech', 'HR', 'Finance'],
    'Manager':    ['Mensah', 'Asante', 'Boateng', 'Adjei']
})

print("Employees:")
print(employees)
print("\nDepartments:")
print(departments)

Employees:
   emp_id   Name  dept_id  Salary
0       1    Ama      101    3200
1       2   Kofi      102    5800
2       3  Abena      101    3900
3       4  Kwame      103    4500
4       5   Efua      102    5100

Departments:
   dept_id Department  Manager
0      101      Sales   Mensah
1      102       Tech   Asante
2      103         HR  Boateng
3      104    Finance    Adjei

In [2]:
inner = pd.merge(employees, departments, on='dept_id', how='inner')
inner

   emp_id   Name  dept_id  Salary Department  Manager
0       1    Ama      101    3200      Sales   Mensah
1       2   Kofi      102    5800       Tech   Asante
2       3  Abena      101    3900      Sales   Mensah
3       4  Kwame      103    4500         HR  Boateng
4       5   Efua      102    5100       Tech   Asante

In [3]:
left = pd.merge(employees, departments, on='dept_id', how='left')
left

   emp_id   Name  dept_id  Salary Department  Manager
0       1    Ama      101    3200      Sales   Mensah
1       2   Kofi      102    5800       Tech   Asante
2       3  Abena      101    3900      Sales   Mensah
3       4  Kwame      103    4500         HR  Boateng
4       5   Efua      102    5100       Tech   Asante

In [4]:
right = pd.merge(employees, departments, on='dept_id', how='right')
right

   emp_id   Name  dept_id  Salary Department  Manager
0     1.0    Ama      101  3200.0      Sales   Mensah
1     3.0  Abena      101  3900.0      Sales   Mensah
2     2.0   Kofi      102  5800.0       Tech   Asante
3     5.0   Efua      102  5100.0       Tech   Asante
4     4.0  Kwame      103  4500.0         HR  Boateng
5     NaN    NaN      104     NaN    Finance    Adjei

In [5]:
# Join first, then analyze
df = pd.merge(employees, departments, on='dept_id', how='inner')

# Average salary per department
df.groupby('Department')['Salary'].mean()

Department
HR       4500.0
Sales    3550.0
Tech     5450.0
Name: Salary, dtype: float64

In [6]:
# Count employees per department
df.groupby('Department')['Name'].count()

Department
HR       1
Sales    2
Tech     2
Name: Name, dtype: int64

In [7]:
# Multiple stats per department
df.groupby('Department')['Salary'].agg(['mean', 'min', 'max', 'count'])

              mean   min   max  count
Department
HR          4500.0  4500  4500      1
Sales       3550.0  3200  3900      2
Tech        5450.0  5100  5800      2